:sectnums:
:numbered:
:toc: macro
:toc-title:
:toclevels: 99

# consul-lb-gce

A smart Google Cloud Engine load-balancer manager for https://www.consul.io/[Consul] backed services.

toc::[]

## Pre-requisites

* Go 1.5.x
* `make`
* Some Go tools
** http://getgb.io[`gb`] - `go get -u github.com/constabulary/gb/...`

## Development

### Build

The following will take care of generating code, build and run tests.
```
make all
```

### Test

To test this locally, you'll need https://github.com/pires/nomad-vagrant-coreos-cluster[a Nomad cluster with Consul integration].
Clone the repo and run:

```
vagrant up
```

You should have one server and two clients running.

Now, before deploying the `nginx` service example, let's compile and run the load-balancer manager. On another terminal window, execute:

```
gb build all
cat config.toml.sample > config.toml

(..edit config.toml accordingly..)

GOOGLE_APPLICATION_CREDENTIALS=~/Work/gce/my-project-1234567890.json bin/consul-lb-google -config config.toml -alsologtostderr
```

You should see something like:
```
I1216 22:06:42.966122   27247 main.go:31] Starting..
I1216 22:06:42.972679   27247 main.go:34] Initializing cloud client [Project ID: my-project-id, Network: my-network, Allowed Zones: []string{"us-east1-d", "europe-west1-d", "asia-east1-c"}]..
I1216 22:06:44.598845   27247 main.go:41] Connecting to Consul at 172.17.9.100:8500..
I1216 22:06:44.600071   27247 main.go:49] Initiating registry..
I1216 22:06:44.600086   27247 main.go:56] Waiting for service updates..
```

Deploy the `nginx` example:

```
nomad run web.hcl
```

Looking at the load-balancer manager terminal window, one should see something like:
```
I1216 22:24:01.046739   27337 main.go:110] Watching service [web].
I1216 22:24:01.046767   27337 cloud.go:81] Creating instance groups for [web]..
I1216 22:24:13.647723   27337 cloud.go:85] Created instance group [asia-east1-c-web] in zone [asia-east1-c].
I1216 22:24:25.731770   27337 cloud.go:85] Created instance group [europe-west1-d-web] in zone [europe-west1-d].
I1216 22:24:54.095646   27337 cloud.go:85] Created instance group [us-east1-d-web] in zone [us-east1-d].
I1216 22:24:54.095671   27337 cloud.go:104] Creating instance groups for [web] completed successfully
```

Now, stop it:

```
nomad stop web
```

Looking again at the load-balancer manager terminal window, one should see something like:

```
I1216 22:34:15.000185   27337 main.go:118] Stopped watching service [web].
I1216 22:34:15.000204   27337 cloud.go:112] Removing instance groups for [web]..
W1216 22:34:27.744633   27337 cloud.go:118] Removed instance group [asia-east1-c-web] from zone [asia-east1-c].
W1216 22:34:39.519136   27337 cloud.go:118] Removed instance group [europe-west1-d-web] from zone [europe-west1-d].
W1216 22:35:07.492766   27337 cloud.go:118] Removed instance group [us-east1-d-web] from zone [us-east1-d].
I1216 22:35:07.492786   27337 cloud.go:130] Removing instance groups for [web] completed successfully
```
