:sectnums:
:numbered:
:toc: macro
:toc-title:
:toclevels: 99

# consul-lb-gce

A smart Google Cloud Engine load-balancer manager for https://www.consul.io/[Consul] backed services.

# Why this project is stopped?

[Answer is here](https://groups.google.com/forum/?hl=EN#!searchin/gce-discussion/network$20endpoint$20group%7Csort:date/gce-discussion/jTP1D77VftY/kZgtNUjcBQAJ)

toc::[]

## Pre-requisites

* Go 1.5.x
* `glide` package manager
* `make`
* A running Nomad cluster with Consul integration on Google Compute Engine
* Necessary DNS record sets
* Firewall rules for necessary endpoints
* Url map which is used to add new host, path rules and path matchers
* Global forwarding rule
* Target HTTP Proxy
* Configured `gcloud` CLI (version should support `network endpoint groups` in beta, necessary project and user)


## Installation
1. `make install`
2. `make release` to build Linux binary (or `make build` to binary without GOOS and GOARCH pre-configurations)
3. Copy `config.toml.sample` as `config.toml` to directory with binary you built before and change it for your requirements
4. `./consul-lb-google -logtostderr=1 -stderrthreshold=INFO` to run it with INFO logging level (just remove these options to have standard logging level)

## Development

To install dependecies run `make install`.

### Build

`make build`

### Test

`make test` for running unit tests.

### Running

**Attention:** Testing locally is not fully supported, but if you're feeling adventurous, take a look at https://github.com/pires/nomad-vagrant-coreos-cluster[this Nomad cluster with Consul integration].

```
./consul-lb-google -logtostderr=1 -stderrthreshold=INFO
```

You should see something like:
```
I1218 16:20:36.877575       1 main.go:45] Starting..
I1218 16:20:36.877909       1 main.go:54] Initializing cloud client [Project ID: my-project, Network: my-network, Allowed Zones: []string{"us-east1-d", "europe-west1-d", "asia-east1-c"}]..
I1218 16:20:36.878178       1 main.go:61] Connecting to Consul at consul.service.consul:8500..
I1218 16:20:36.878198       1 main.go:69] Initiating registry..
I1218 16:20:36.878214       1 main.go:76] Waiting for service updates..
```

### How it works

The service is polling Consul on running services. For groups of services with watched tags it creates network endpoint group, health check, backend service and adds host and path rules (according to tag) to existing url map and navigates requests to created backend service. After created NEG is populated or depopulated with endpoints.

_For example:_

1. Watched tag is single and it is `tagprefix-cdn-ipaffinity-test.domain.com/`.
2. App creates network endpoint group `neg-tagprefix-cdn-ipaffinity-test-domain-com` or use existing one.
3. App creates health check 'http-hc-neg-tagprefix-cdn-ipaffinity-test-domain-com' or use existing one.
4. App creates backend service with NEG and HC created above, also with cdn and affinity configurations if they are specified.
5. App adds (if not exist) host rule for `test.domain.com` with patch matcher for `/*` targeted to created backend service.
* If path has not only `/` (e.g.: `/path`) then it creates `/test*` path matcher and targets it to created backend, but `/*` is navigated to default backend service in url map.


### Tag format

Tag has following format `${TAG_PREFIX}${CDN}-${AFFINITY}-${HOST}${PATH}`, e.g.: _tagprefix-cdn-ipaffinity-test.domain.com/_.

`CDN` can have values: `'nocdn'` or `'cdn'`.

`AFFINITY` can have values: `'ipaffinity'` or `'noaffinity'`.

### Configuration

You can look at example of configuration in `config.toml.sample`.

Note: There are health checks paths must be specified since they can't be retrieved from Consul.
